### ISSUE TITLE
TensorFlow Checkpoint Error When using roslaunch 

### ISSUE THREAD

**Issue by heshamnimri** [AbangLZU/LaneNetRos#9]
I have setup the project as suggested and made minimal alterations, however when I try to roslaunch the project using maybeshewill-CV's weights I get the following error: 

`
2019-08-01 14:20:11.349834: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_1_fuse/fuse_conv/W not found in checkpoint
Traceback (most recent call last):
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 138, in <module>
    lanenet_detector()
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 38, in __init__
    self.init_lanenet()
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 76, in init_lanenet
    saver.restore(sess=self.sess, save_path="/home/lonpc000698/catkin_ws/src/LaneNetRos/model/tusimple_lanenet_vgg.ckpt")
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1743, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_1_fuse/fuse_conv/W not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 138, in <module>
    lanenet_detector()
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 38, in __init__
    self.init_lanenet()
  File "/home/lonpc000698/catkin_ws/src/LaneNetRos/scripts/lanenet_node.py", line 58, in init_lanenet
    saver = tf.train.Saver()
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/lonpc000698/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_1_fuse/fuse_conv/W not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

`

Any ideas as to why this is happening ? Is it related to the python packages or something else ?

**Comment by rgh78910** [comment]
Same here!!

**Comment by rgh78910** [comment]
@MHN-II Did you find how to fix this?

**Comment by jjimin** [comment]
I think the variable named ```/fuse_conv``` has a problem.

This variable is defined in the file ```LaneNetRos/scripts/semantic_segmentation_zoo/vgg16_based_fcn.py``` as shown below.

```
fuse_feats = self.conv2d(
                inputdata=fuse_feats,
                out_channel=out_channels_nums,
                kernel_size=3,
                padding='SAME',
                stride=1,
                w_init=conv_weights_init,
                use_bias=use_bias,
                name='fuse_conv'
            )
```
To fix this, I just changed this invalid file to an original file(```semantic_segmentation_zoo/vgg16_based_fcn.py```) of [MaybeShewill-CV /lanenet-lane-detection github](https://github.com/MaybeShewill-CV/lanenet-lane-detection.git).

Then it works!
